export const langArr = {
  'en': {
    'skills': 'Skills',
    'portfolio': 'Portfolio',
    'contacts': 'Contacts',
    'from': 'Krasnodar, Russia',
    'hello': "Hello, I'm Natalia",
    'profession': 'web-developer',
    'development': 'I am engaged in the development of modern websites and applications, adapt sites for mobile devices. I specialize in Frontend development, but I can also solve not complicated tasks on the Backend.',
    'skillsTitle':'Skills',
    'artemida': 'Accounting services website',
    'view':'View site',
    'cable':'Cable sales company website',
    'kolibry':'Furniture atelier website',
    'lawyer':'Law firm website',
    'pexeso':'Pexeso Game',
    'crm':'CRM for furniture company',
    'phone':'Phone Book',
    'card':'Business card website',
    'burger':'Burger website',
    'vk':'vk'
  },
  'ru': {
    'skills': 'Скилы',
    'portfolio': 'Портфолио',
    'contacts': 'Контакты',
    'from': 'Краснодар, Россия',
    'hello': "Привет, я Наталья",
    'profession': 'веб-разработчик',
    'development': 'Занимаюсь разработкой современных сайтов и приложений, адаптирую сайты под мобильные устройства. Специализируюсь на Frontend разработке, но также могу решать не сложные задачи на Backend.',
    'skillsTitle' : 'Ключевые навыки',
    'artemida': 'Сайт бухгалтерских услуг',
    'view':'Посмотреть',
    'cable':'Сайт компании по продаже кабеля',
    'kolibry':'Сайт ателье мебели',
    'lawyer':'Сайт юридической компании',
    'pexeso':'Игра Pexeso',
    'crm':'CRM для мебельной компании',
    'phone':'Телефонная книга',
    'card':'Сайт-визитка',
    'burger':'Сайт бургерной',
    'vk':'ВКонтакте'
  }
}